# Generated by Django 3.1.2 on 2023-04-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230429_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateField(null=True),
        ),
    ]
